package runner;
import com.github.javafaker.Faker;
import cucumber.api.junit.Cucumber;
import featureSteps.AddPet;
import featureSteps.TestPetStore;
import net.thucydides.core.annotations.Steps;
import org.junit.Test;
import org.junit.runner.RunWith;
import cucumber.api.CucumberOptions;

@RunWith(Cucumber.class)
@CucumberOptions(
        features="features",
        glue= "featureSteps",
        plugin={"json:target/cucumber.json","pretty","html:target/cucumber-reports"}
)

public class TestRunnerNew {

    @Steps
    TestPetStore petStore;

    @Test
    public void AddingToPetToAStore() {

        //auto generate random name for pet
        Faker faker = new Faker();
        String petName=faker.name().firstName();

        AddPet fido = new AddPet("available", petName);

        petStore.iAddAPetWithAutoGeneratedNameAndMakeItAvailableOnList(fido);
        petStore.iShouldGetResultsOfMyPetWhenISearchWithId();
    }

}

